import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto, Poppins, Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar";
import { cn } from "@/lib/utils";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, poppins.className, "font-sans", inter.variable)}
    >
      <body className="min-h-full flex p-2 gap-2">
        <div>
          <NavBar/>
        </div>
        <main className="main-scrollbar h-full w-full rounded-lg overflow-y-auto">
          {children}
        </main>
        </body>
    </html>
  );
}
